ignore aide errors, since they are not errors

diff --git a/jobs/harden/templates/bin/post-deploy b/jobs/harden/templates/bin/post-deploy
--- a/jobs/harden/templates/bin/post-deploy
+++ b/jobs/harden/templates/bin/post-deploy
@@ -257,5 +257,7 @@ apt-get upgrade -y tcpd
 echo "---> Finished hardening process"
 if [[ -f /var/vcap/jobs/aide/bin/update-aide-db ]]; then
   echo "---> Updating AIDE db"
+  set +e # aide returns non-zero on db changes
   /var/vcap/jobs/aide/bin/update-aide-db
+  set -e
 fi
